---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos9-stream
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
