---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    #image: quay.io/centos/centos:stream9
    image: rockylinux:9
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
