---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    #image: quay.io/centos/centos:stream8
    #image: centos:7
    image: dokken/centos-8
    #image: centos:7
    #image: quay.io/centos/centos:stream9
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
