---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: dokken/centos-stream-9:latest
    command: /sbin/init
    privileged: True
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
